'use strict';
const $=s=>document.querySelector(s);
const labels={nao_verificado:'Não verificado',pendente:'Pendente',em_andamento:'Em andamento',confirmado:'Confirmado',bloqueado:'Bloqueado',nao_se_aplica:'Não se aplica'};
const model={groups:[],fields:[],schema:null};
function node(tag,text,cls){const el=document.createElement(tag);if(text)el.textContent=text;if(cls)el.className=cls;return el;}
function labelFor(value){return labels[value]||value.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());}
function safeUrl(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:null}catch{return null}}
function reportValue(f){const el=document.getElementById('value-'+f.id);return el?.value.trim()||null;}
function confirmed(f){const v=reportValue(f);return f.type==='id'?Boolean(v&&/^\d{8,30}$/.test(v)):Boolean(v);}
function update(){let done=0;for(const group of model.groups){let n=0;for(const f of group.fields)if(confirmed(f))n++;done+=n;document.getElementById('count-'+group.id).textContent=n+' / '+group.fields.length+' preenchidos';}$('#progress').value=model.fields.length?100*done/model.fields.length:0;$('#progress-text').textContent=done+' de '+model.fields.length+' itens preenchidos';$('#progress-detail').textContent='Preencher IDs não comprova que o acesso funciona.';}
function validate(){let valid=true;for(const f of model.fields){if(f.type!=='id')continue;const el=document.getElementById('value-'+f.id);const bad=el.value&&!/^\d{8,30}$/.test(el.value);el.setCustomValidity(bad?'Use somente o identificador numérico, de 8 a 30 dígitos. Não cole tokens.':'');document.getElementById('error-'+f.id).textContent=bad?'Use só o ID numérico. Tokens e segredos ficam fora deste formulário.':'';if(bad){valid=false;el.closest('details').open=true;}}if(!valid){$('#action-status').textContent='Corrija os identificadores destacados antes de baixar ou copiar.';$('#checklist').reportValidity();}return valid;}
function summary(){if(!validate())return null;const lines=['TEDDY + WEBi | Checklist Meta','Preenchido em '+new Date().toLocaleString('pt-BR'),'', 'Resumo preparado no navegador. Não foi enviado automaticamente.','IDs e situações informados pelo responsável; validação técnica ainda necessária.',''];for(const g of model.groups){lines.push(g.title);for(const f of g.fields){const val=reportValue(f);lines.push('- '+f.label+': '+(val?(f.type==='id'?val:labelFor(val)):'Não informado')+' | Responsável: '+f.owner);}lines.push('');}lines.push('Credenciais: compartilhar apenas no cofre ou canal privado combinado com a WEBi.','Nunca incluir senha, token, App Secret, PIN, dados de cartão ou códigos de verificação.');return lines.join('\n');}
async function load(){try{const r=await fetch('checklist-data.json',{cache:'no-cache'});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();model.groups=data.groups;model.fields=data.groups.flatMap(g=>g.fields);model.schema=data.dataSchema;const form=$('#checklist');form.replaceChildren();
for(const [i,g] of model.groups.entries()){const details=node('details',null,'group');details.open=i===0;const s=node('summary');s.append(node('span',String(i+1).padStart(2,'0'),'num'),node('span',g.title.replace(/^\d+\.\s*/,''),'title'));const count=node('span','','count');count.id='count-'+g.id;s.append(count,node('span','+','arrow'));details.append(s,node('p',g.description,'group-description'));const fields=node('div',null,'fields');
for(const f of g.fields){const row=node('div',null,'field');row.dataset.field=f.id;const info=node('div');const title=node('h3',f.label);title.id='title-'+f.id;info.append(node('span',f.owner,'owner'),title,node('p',f.help,'help'),node('p','Onde encontrar: '+f.path,'path'));const url=safeUrl(f.uiUrl);if(url){const a=node('a','Abrir painel Meta ↗','source');a.href=url;a.target='_blank';a.rel='noopener noreferrer';info.append(a);}const area=node('div',null,'input-area');const label=node('label',f.type==='id'?'Identificador numérico'+(f.required?'':' · se aplicável'):'Situação atual');label.htmlFor='value-'+f.id;area.append(label);let input;
if(f.type==='id'){input=node('input');input.type='text';input.inputMode='numeric';input.pattern='[0-9]{8,30}';input.maxLength=30;input.placeholder='Somente o ID, sem token';input.autocomplete='off';input.spellcheck=false;input.addEventListener('input',()=>{input.setCustomValidity('');document.getElementById('error-'+f.id).textContent='';});}else{input=node('select');input.append(new Option('Selecionar situação',''));for(const opt of f.options)input.append(new Option(labelFor(opt),opt));}
input.id='value-'+f.id;input.name=f.id;input.setAttribute('aria-labelledby',title.id+' '+label.htmlFor+'-label');label.id=label.htmlFor+'-label';input.addEventListener('change',update);input.addEventListener('input',update);area.append(input);if(f.type==='id'){const error=node('span','','error');error.id='error-'+f.id;error.setAttribute('aria-live','polite');input.setAttribute('aria-describedby',error.id);area.append(error);}row.append(info,area);fields.append(row);}details.append(fields);form.append(details);}
if(data.privateItems?.length){const block=node('details',null,'group');const s=node('summary');s.append(node('span','↗','num'),node('span','Credenciais em canal privado','title'),node('span','+','arrow'));block.append(s);const list=node('div',null,'fields');for(const p of data.privateItems){const item=node('div',null,'field');const content=node('div');content.append(node('span',p.owner||'','owner'),node('h3',p.label),node('p',p.instruction,'help'));if(p.steps){const steps=node('ol',null,'credential-steps');p.steps.forEach(t=>steps.append(node('li',t)));content.append(steps);}item.append(content,node('p','Não preencher nesta página.','owner'));list.append(item);}block.append(list);form.append(block);}
form.addEventListener('submit',e=>e.preventDefault());$('#download').disabled=false;$('#copy').disabled=false;update();}
catch(error){$('#loading').textContent='Não foi possível carregar o checklist. Atualize a página ou peça o arquivo à WEBi.';$('#progress-text').textContent='Checklist indisponível';console.error(error);}}
$('#download').addEventListener('click',()=>{const text=summary();if(text===null)return;const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/plain;charset=utf-8'}));const a=node('a');a.href=url;a.download='teddy-webi-checklist-meta.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#action-status').textContent='Resumo baixado. Encaminhe o arquivo à equipe WEBi.';});
$('#copy').addEventListener('click',async()=>{const text=summary();if(text===null)return;try{await navigator.clipboard.writeText(text);$('#action-status').textContent='Resumo copiado. Cole na conversa com a equipe WEBi.';}catch{$('#action-status').textContent='A cópia foi bloqueada pelo navegador. Use “Baixar resumo”.';}});
let beforePrintState=null;
window.addEventListener('beforeprint',()=>{const sections=[...document.querySelectorAll('details')];beforePrintState=sections.map(d=>d.open);sections.forEach(d=>d.open=true);});
window.addEventListener('afterprint',()=>{if(beforePrintState){document.querySelectorAll('details').forEach((d,i)=>d.open=beforePrintState[i]);beforePrintState=null;}});
$('#print').addEventListener('click',()=>window.print());
load();
